@AdditionApi_HostAddress = http://localhost:5262

### Save data (like localStorage.setItem)
POST {{AdditionApi_HostAddress}}/data
Content-Type: application/json

{
  "key": "addition_result",
  "value": "45"
}

###

### Get data (like localStorage.getItem)
GET {{AdditionApi_HostAddress}}/data/addition_result
Accept: application/json