@AdditionApi_HostAddress = http://localhost:5262

###### Post data ###
POST {{AdditionApi_HostAddress}}/storage
Content-Type: application/json

{
  "key": "result",
  "value": "42"
}

###

### Get data
GET {{AdditionApi_HostAddress}}/storage/result
Accept: application/json